export const blogCategories = [
  "Technology",
  "Health",
  "Lifestyle",
  "Travel",
  "Education",
  "Finance",
  "Food",
  "Entertainment",
  "Fashion",
  "Sports",
  "Science",
  "Politics",
  "Business",
  "Art",
  "History",
  "Environment",
  "Music",
  "Gaming",
  "Automotive",
  "Real Estate",
  "Parenting",
  "Photography",
  "Self-Improvement",
  "Mental Health",
  "Relationships",
  "Pets",
  "DIY",
  "Home Improvement",
  "Gardening",
  "Cooking",
  "Writing",
  "Cryptocurrency",
  "Web Development",
  "Mobile Development",
  "Data Science",
  "Artificial Intelligence",
  "Machine Learning",
  "Cloud Computing",
  "Cybersecurity",
  "Blockchain",
  "Virtual Reality",
  "Augmented Reality",
  "Social Media",
  "Digital Marketing",
  "E-commerce",
  "Startups",
  "Nonprofit",
  "Philanthropy",
  "Travel Tips",
  "Cultural Insights",
  "Local Events",
  "Book Reviews",
  "Movie Reviews",
  "Music Reviews",
  "Product Reviews",
  "Tech News",
  "Health Tips",
  "Fitness",
  "Wellness",
  "Nutrition",
  "Mental Wellness",
  "Personal Finance",
  "Investment",
  "Retirement Planning",
  "Insurance",
  "Real Estate Investing",
  "Stock Market",
  "Cryptocurrency Investing",
  "Small Business",
  "Entrepreneurship",
  "Leadership",
  "Career Development",
  "Work-Life Balance",
  "Remote Work",
  "Freelancing",
  "Job Search",
  "Resume Tips",
  "Interview Tips",
  "Networking",
  "Public Speaking",
  "Time Management",
  "Productivity",
  "Goal Setting",
  "Mindfulness",
  "Stress Management",
  "Personal Development",
  "Life Hacks",
  "Motivation",
  "Inspiration",
  "Success Stories",
  "Failure Stories",
  "Lessons Learned",
  "Case Studies",
  "Opinion Pieces",
  "Interviews",
  "Guest Posts",
  "How-To Guides",
];
